---

#  ansible.builtin.template:
#    src: 'potos.example.j2'
#    dest: '/potos.example'
#    owner: root
#    group: root
#    mode: '0755'

- name: copy files
  ansible.builtin.template:
    src: "{{ potos_files.src }}"
    dest: "{{ potos_files.dest }}"
    owner: "{{ potos_files.owner }}"
    group: "{{ potos_files.group }}"
    mode: "{{ potos_files.mode }}"

